### ISSUE TITLE
Keyword Searching should use a regex

### ISSUE THREAD

**Issue by tomrittervg** [cryptodotis/code-peer-review#7]
Currently we just look to see if a word appears with spaces surrounding it.  This should be changed to any nonalphanumeric character like underscores or dashes.

**Comment by sigmavirus24** [comment]
Which module would this be implemented in? It should be fairly easy to implement.

**Comment by tomrittervg** [comment]
It's happening right here:
https://github.com/cryptodotis/code-audit-feed/blob/master/commit.py#L93

if lk in log:  < if the space-surrounded keyword is in the log message
if pk in p:   < if the slash-prepended keyword is found in a file path

So tor would match "Happy tor Birthday" in message log and "/torbob" in the file path
But not "Tornado" or "/prepfortornado".
