### ISSUE TITLE
Keyword Searching should occur inside the actual diff

### ISSUE THREAD

**Issue by tomrittervg** [cryptodotis/code-peer-review#8]
Currently keyword searching only happens in the commit message and filenames.  It should look inside the diff also - but not match inside words.  See also: the regex issue

**Comment by tomrittervg** [comment]
Iterate over the tuple generated here: https://github.com/cryptodotis/code-audit-feed/commit/6cbeffabba676b3d3551302a4e49dcfc71af07c0#L1R75 and do matching on -1's and 1's.  Also look for things matching in file additions.  (But not renames or deletions.)  See http://code.google.com/p/google-diff-match-patch/wiki/API

**Comment by sigmavirus24** [comment]
This looks like it should be fun to work on.

**Comment by tomrittervg** [comment]
This should now be working for subversion and git
